In [1]:
import os
os.getcwd()

'C:\\Users\\dreyl2'

In [1]:
import pandas as pd
%pylab inline

Populating the interactive namespace from numpy and matplotlib

In [2]:
X = pd.read_csv("RedditShortDemoSurvey-1-Cleaned.csv")

In [3]:
X

,ID,Gender,Age,Marital_Status,Employment_Status,Military_Service,Children_under_18,Education,Country,Continent,Income,treated_subreddit_data,Dog_Cat,Cheese
0,1,Male,25-34,Blank,Employed full time,none,No,Bachelor's degree,United States,North America,"$150,000 or more",getmotivated,none,none
1,2,Male,25-34,Blank,Employed full time,none,No,Bachelor's degree,United States,North America,"$150,000 or more",gaming,none,none
2,3,Female,18-24,Blank,Freelance,none,No,Some college,United States,North America,"Under $20,000",snackexchange,none,none
3,4,Male,25-34,Blank,Freelance,none,No,Bachelor's degree,United States,North America,"$150,000 or more",spacedicks,none,none
4,5,Female,25-34,Blank,Employed full time,none,No,Bachelor's degree,United States,North America,"$70,000 - $99,999",aww,none,none
5,6,Male,25-34,Married/civil union/domestic partnership,Employed full time,No,No,Bachelor's degree,United States,North America,"$150,000 or more",gaming,I like dogs.,Cheddar
6,7,Male,25-34,In a relationship,Employed full time,No,No,Some college,Germany,Europe,none,python,I like dogs.,Cheddar
7,8,Male,18-24,Married/civil union/domestic partnership,"Not employed, but looking for work",No,No,Bachelor's degree,United States,North America,"$70,000 - $99,999",fffffffuuuuuuuuuuuu,I like dogs.,American
8,9,Male,35-44,Married/civil union/domestic partnership,Employed full time,No,No,Bachelor's degree,United States,North America,"$150,000 or more",todayilearned,I like cats.,Provolone
9,10,Male,25-34,In a relationship,Freelance,No,No,Some college,Germany,Europe,"$70,000 - $99,999",NaN,I like cats.,Munster
10,11,Male,18-24,Forever Alone,Not employed and not looking for work,No,No,High school graduate or equivalent,United States,North America,"Under $20,000",gaming,I like dogs.,Cheddar
11,12,Male,18-24,In a relationship,Employed full time,No,No,Bachelor's degree,United States,North America,"$40,000 - $49,999",machinelearning,I like dogs.,Swiss
12,13,Male,25-34,Forever Alone,Employed full time,No,No,Bachelor's degree,United States,North America,"$50,000 - $69,999",starcraft,I like turtles.,Provolone
13,14,Male,18-24,Forever Alone,Student,No,No,Some college,Romania,Europe,"Under $20,000",NaN,I like cats.,Swiss
14,15,Male,25-34,In a relationship,Employed full time,No,No,Bachelor's degree,United States,North America,"$50,000 - $69,999",technology,I like dogs.,Provolone
15,16,Male,18-24,In a relationship,Student,No,No,Some college,United States,North America,"Under $20,000",askreddit,I like cats.,Cheddar
16,17,Female,25-34,In a relationship,Employed full time,No,No,Some college,United States,North America,"$50,000 - $69,999",twoxchromosomes,I like cats.,Goat
17,18,Male,35-44,Single,Not employed and not looking for work,No,No,Graduate or professional degree,England,Europe,"Under $20,000",aww,I like cats.,Goat
18,19,Male,25-34,Single,Employed full time,No,No,Graduate or professional degree,Ireland,Europe,"$40,000 - $49,999",askscience,I like cats.,Feta
19,20,Male,25-34,In a relationship,Employed full time,No,No,Bachelor's degree,United States,North America,"$70,000 - $99,999",android,I like dogs.,Feta
20,21,Male,45-54,Married/civil union/domestic partnership,Freelance,No,Yes,High school graduate or equivalent,France,Europe,"Under $20,000",motorcycles,I like dogs.,Cheddar
21,22,Male,Under 18,Forever Alone,Student,No,Yes,High school graduate or equivalent,England,Europe,"$100,000 - $149,999",anarchism,I like turtles.,Swiss
22,23,Male,18-24,Single,Employed full time,No,No,High school graduate or equivalent,Germany,Europe,"$100,000 - $149,999",truereddit,I like cats.,Other
23,24,Male,55-64,Forever Alone,Employed full time,Yes,No,Trade or Vocational degree,Canada,North America,"$40,000 - $49,999",atheism,I like cats.,Feta
24,25,Male,45-54,Married/civil union/domestic partnership,Freelance,No,No,Some college,Germany,Europe,"$150,000 or more",new,I like turtles.,Other
25,26,Female,25-34,Single,Student,No,No,Graduate or professional degree,United States,North America,"Under $20,000",adviceanimals,I like dogs.,Brie
26,27,Male,25-34,Forever Alone,Employed full time,No,No,Bachelor's degree,United States,North America,"$50,000 - $69,999",programming,I like dogs.,Cheddar
27,28,None,25-34,In a relationship,"Not employed, but looking for work",No,No,Graduate or professional degree,United States,North America,"Under $20,000",askscience,I like dogs.,Brie
28,29,Male,18-24,Single,Employed full time,No,No,Some college,United States,North America,"$20,000 - $29,999",pics,I like dogs.,Swiss
29,30,Female,18-24,Forever Alone,Student,No,No,Some college,United States,North America,none,NaN,I like dogs.,American
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32724,32727,Male,18-24,In a relationship,Student,No,No,Some college,United States,North America,"$30,000 - $39,999",starcraft,I like dogs.,Provolone
32725,32728,Male,25-34,Married/civil union/domestic partnership,Employed full time,No,Yes,Some college,United States,North America,"$100,000 - $149,999",NaN,I like dogs.,Other
32726,32729,Male,18-24,Single,Student,No,No,Some college,United States,North America,"$30,000 - $39,999",NaN,I like dogs.,American
32727,32730,Male,18-24,Single,Student,No,No,High school graduate or equivalent,Belgium,Europe,"Under $20,000",pics,I like cats.,Other
32728,32731,Female,18-24,In a relationship,"Not employed, but looking for work",No,No,Bachelor's degree,United States,North America,"$50,000 - $69,999",questions,I like turtles.,Swiss
32729,32732,Male,Under 18,Single,Student,No,No,Some high school,United States,North America,"$30,000 - $39,999",starcraft,I like dogs.,Swiss
32730,32733,Male,18-24,Single,Freelance,No,No,High school graduate or equivalent,United States,North America,"$100,000 - $149,999",fffffffuuuuuuuuuuuu,I like cats.,Cheddar
32731,32734,Female,25-34,Engaged,None,No,No,Associate degree,NaN,NaN,"$40,000 - $49,999",NaN,I like dogs.,Cheddar
32732,32735,Male,18-24,Single,Student,No,No,High school graduate or equivalent,Canada,North America,"$150,000 or more",NaN,I like dogs.,Goat
32733,32736,Female,25-34,In a relationship,Employed full time,No,No,Bachelor's degree,United States,North America,"$40,000 - $49,999",NaN,I like turtles.,Brie
32734,32737,Female,Under 18,Single,None,Yes,No,Some high school,United States,North America,"Under $20,000",fffffffuuuuuuuuuuuu,I like cats.,Feta
32735,32738,Female,18-24,Married/civil union/domestic partnership,Employed full time,No,No,Bachelor's degree,United States,North America,"$30,000 - $39,999",pics,I like cats.,Provolone
32736,32739,Male,18-24,Married/civil union/domestic partnership,"Not employed, but looking for work",Yes,No,Bachelor's degree,United States,North America,"$20,000 - $29,999",iama,I like cats.,Paneer
32737,32740,Male,18-24,Forever Alone,Employed full time,Yes,No,Associate degree,United States,North America,"$30,000 - $39,999",netsec,I like turtles.,Munster
32738,32741,Male,25-34,Single,Employed full time,No,No,Some college,Australia,Oceania,"$50,000 - $69,999",NaN,I like turtles.,Brie
32739,32742,Male,Under 18,Single,Student,No,No,High school graduate or equivalent,United States,North America,"$50,000 - $69,999",shutupandtakemymoney,I like cats.,American
32740,32743,Male,18-24,Single,Student,No,No,Graduate or professional degree,United States,North America,"Under $20,000",math,I like dogs.,Provolone
32741,32744,Male,Under 18,Forever Alone,Student,Yes,Yes,Some high school,United States,North America,none,gurrenlagann,I like cats.,American
32742,32745,Male,18-24,In a relationship,Student,No,No,Some college,Australia,Oceania,"$50,000 - $69,999",pics,I like dogs.,Cheddar
32743,32746,Male,18-24,In a relationship,Student,No,No,Some college,United States,North America,"$20,000 - $29,999",askreddit,I like cats.,Other
32744,32747,Male,Under 18,In a relationship,Freelance,No,Yes,Some high school,United States,North America,"$40,000 - $49,999",firstworldproblems,I like turtles.,American
32745,32748,Male,45-54,Single,Employed full time,No,No,Associate degree,United States,North America,"$20,000 - $29,999",NaN,I like cats.,Brie
32746,32749,Male,Under 18,Single,Student,No,None,Some high school,Canada,North America,"$50,000 - $69,999",funny,I like cats.,Swiss
32747,32750,Male,25-34,In a relationship,Freelance,No,No,Bachelor's degree,United States,North America,"Under $20,000",NaN,I like cats.,Cheddar
32748,32751,Male,25-34,In a relationship,Employed full time,Yes,No,Bachelor's degree,Japan,Asia,"$150,000 or more",NaN,I like dogs.,Provolone
32749,32752,Female,18-24,Single,Student,No,No,High school graduate or equivalent,Denmark,Europe,"Under $20,000",NaN,I like cats.,Feta
32750,32753,Male,35-44,Married/civil union/domestic partnership,Employed full time,No,No,Bachelor's degree,England,Europe,none,maps,I like turtles.,Other
32751,32754,Male,18-24,In a relationship,Employed full time,No,No,Graduate or professional degree,England,Europe,"$20,000 - $29,999",funny,I like cats.,Other
32752,32755,Male,35-44,In a relationship,Employed full time,No,Yes,Bachelor's degree,United States,North America,"$100,000 - $149,999",NaN,I like cats.,Swiss
32753,32756,Male,18-24,Married/civil union/domestic partnership,Employed full time,No,No,Some college,United States,North America,"$20,000 - $29,999",fffffffuuuuuuuuuuuu,I like cats.,Cheddar

In [6]:
y = X.Income
y

0           $150,000 or more
1           $150,000 or more
2              Under $20,000
3           $150,000 or more
4          $70,000 - $99,999
5           $150,000 or more
6                       none
7          $70,000 - $99,999
8           $150,000 or more
9          $70,000 - $99,999
10             Under $20,000
11         $40,000 - $49,999
12         $50,000 - $69,999
13             Under $20,000
14         $50,000 - $69,999
15             Under $20,000
16         $50,000 - $69,999
17             Under $20,000
18         $40,000 - $49,999
19         $70,000 - $99,999
20             Under $20,000
21       $100,000 - $149,999
22       $100,000 - $149,999
23         $40,000 - $49,999
24          $150,000 or more
25             Under $20,000
26         $50,000 - $69,999
27             Under $20,000
28         $20,000 - $29,999
29                      none
                ...
32724      $30,000 - $39,999
32725    $100,000 - $149,999
32726      $30,000 - $39,999
32727          Under $20,000
32728      $50,000 - $69,999
32729      $30,000 - $39,999
32730    $100,000 - $149,999
32731      $40,000 - $49,999
32732       $150,000 or more
32733      $40,000 - $49,999
32734          Under $20,000
32735      $30,000 - $39,999
32736      $20,000 - $29,999
32737      $30,000 - $39,999
32738      $50,000 - $69,999
32739      $50,000 - $69,999
32740          Under $20,000
32741                   none
32742      $50,000 - $69,999
32743      $20,000 - $29,999
32744      $40,000 - $49,999
32745      $20,000 - $29,999
32746      $50,000 - $69,999
32747          Under $20,000
32748       $150,000 or more
32749          Under $20,000
32750                   none
32751      $20,000 - $29,999
32752    $100,000 - $149,999
32753      $20,000 - $29,999
Name: Income, dtype: object

In [8]:
dummies = pd.get_dummies(X['Income'], prefix='Income')
y = pd.concat([y, dummies], axis=1)
y

,Income,"Income_$100,000 - $149,999","Income_$150,000 or more","Income_$20,000 - $29,999","Income_$30,000 - $39,999","Income_$40,000 - $49,999","Income_$50,000 - $69,999","Income_$70,000 - $99,999","Income_Under $20,000",Income_none,"Income_$100,000 - $149,999","Income_$150,000 or more","Income_$20,000 - $29,999","Income_$30,000 - $39,999","Income_$40,000 - $49,999","Income_$50,000 - $69,999","Income_$70,000 - $99,999","Income_Under $20,000",Income_none
0,"$150,000 or more",0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1,"$150,000 or more",0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
2,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
3,"$150,000 or more",0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,"$70,000 - $99,999",0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
5,"$150,000 or more",0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
6,none,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
7,"$70,000 - $99,999",0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
8,"$150,000 or more",0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
9,"$70,000 - $99,999",0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
10,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
11,"$40,000 - $49,999",0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
12,"$50,000 - $69,999",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
13,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
14,"$50,000 - $69,999",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
15,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
16,"$50,000 - $69,999",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
17,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
18,"$40,000 - $49,999",0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
19,"$70,000 - $99,999",0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
20,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
21,"$100,000 - $149,999",1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
22,"$100,000 - $149,999",1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
23,"$40,000 - $49,999",0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
24,"$150,000 or more",0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
25,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
26,"$50,000 - $69,999",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
27,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
28,"$20,000 - $29,999",0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
29,none,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32724,"$30,000 - $39,999",0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
32725,"$100,000 - $149,999",1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
32726,"$30,000 - $39,999",0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
32727,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
32728,"$50,000 - $69,999",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
32729,"$30,000 - $39,999",0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
32730,"$100,000 - $149,999",1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
32731,"$40,000 - $49,999",0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
32732,"$150,000 or more",0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
32733,"$40,000 - $49,999",0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
32734,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
32735,"$30,000 - $39,999",0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
32736,"$20,000 - $29,999",0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
32737,"$30,000 - $39,999",0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
32738,"$50,000 - $69,999",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
32739,"$50,000 - $69,999",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
32740,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
32741,none,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
32742,"$50,000 - $69,999",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
32743,"$20,000 - $29,999",0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
32744,"$40,000 - $49,999",0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
32745,"$20,000 - $29,999",0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
32746,"$50,000 - $69,999",0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
32747,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
32748,"$150,000 or more",0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
32749,"Under $20,000",0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
32750,none,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
32751,"$20,000 - $29,999",0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
32752,"$100,000 - $149,999",1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
32753,"$20,000 - $29,999",0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [9]:
X.drop(['Income'], axis=1, inplace=True)

In [10]:
y.drop(['Income'], axis=1, inplace=True)

In [11]:
X.drop(["treated_subreddit_data"], axis=1, inplace=True)

In [12]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import roc_auc_score

In [13]:
X.describe()

                 ID
count  32754.000000
mean   16378.561916
std     9456.272427
min        1.000000
25%     8189.250000
50%    16379.500000
75%    24567.750000
max    32756.000000

In [14]:
model = RandomForestRegressor(n_estimators=100, oob_score=True, random_state=42)

In [15]:
def describe_categorical(X):
    from IPython.display import display, HTML
    display(HTML(X[X.columns[X.dtypes == 'object']].describe().to_html()))

In [16]:
describe_categorical(X)

In [17]:
X.drop(["Country"], axis=1, inplace=True)

In [18]:
describe_categorical(X)

In [19]:
categorical_variables = ['Gender', 'Age', 'Marital_Status', 'Employment_Status', 'Military_Service', 'Children_under_18', 'Education', 'Continent', 'Dog_Cat', 'Cheese']

for variable in categorical_variables:
    X[variable].fillna("Missing", inplace=True)
    dummies = pd.get_dummies(X[variable], prefix=variable)
    X = pd.concat([X, dummies], axis=1)
    X.drop([variable], axis=1, inplace=True)

In [20]:
X

,ID,Gender_Female,Gender_Male,Gender_None,Age_18-24,Age_25-34,Age_35-44,Age_45-54,Age_55-64,Age_65 or Above,...,Cheese_Cheddar,Cheese_Feta,Cheese_Goat,Cheese_Limburger,Cheese_Munster,Cheese_Other,Cheese_Paneer,Cheese_Provolone,Cheese_Swiss,Cheese_none
0,1,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,2,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,3,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,4,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,5,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
5,6,0,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
6,7,0,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
7,8,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
9,10,0,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
10,11,0,1,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
11,12,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
12,13,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
13,14,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
14,15,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
15,16,0,1,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
16,17,1,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
17,18,0,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
18,19,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
19,20,0,1,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
20,21,0,1,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
21,22,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
22,23,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
23,24,0,1,0,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
24,25,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
25,26,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
26,27,0,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
27,28,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
28,29,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
29,30,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32724,32727,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32725,32728,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
32726,32729,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32727,32730,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
32728,32731,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
32729,32732,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
32730,32733,0,1,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
32731,32734,1,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
32732,32735,0,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
32733,32736,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32734,32737,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
32735,32738,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32736,32739,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
32737,32740,0,1,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
32738,32741,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32739,32742,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32740,32743,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32741,32744,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32742,32745,0,1,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
32743,32746,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
32744,32747,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
32745,32748,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
32746,32749,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
32747,32750,0,1,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
32748,32751,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
32749,32752,1,0,0,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
32750,32753,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
32751,32754,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
32752,32755,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
32753,32756,0,1,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [21]:
def printall(X, max_rows=10):
    from IPython.display import display, HTML
    display(HTML(X.to_html(max_rows=max_rows)))
    
printall(X)

In [22]:
y

,"Income_$100,000 - $149,999","Income_$150,000 or more","Income_$20,000 - $29,999","Income_$30,000 - $39,999","Income_$40,000 - $49,999","Income_$50,000 - $69,999","Income_$70,000 - $99,999","Income_Under $20,000",Income_none,"Income_$100,000 - $149,999","Income_$150,000 or more","Income_$20,000 - $29,999","Income_$30,000 - $39,999","Income_$40,000 - $49,999","Income_$50,000 - $69,999","Income_$70,000 - $99,999","Income_Under $20,000",Income_none
0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
3,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
5,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
7,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
8,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
9,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
10,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
11,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
12,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
13,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
14,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
15,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
16,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
17,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
18,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
19,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0
20,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
21,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
22,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
23,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
24,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
25,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
26,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
27,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
28,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32724,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
32725,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
32726,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
32727,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
32728,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
32729,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
32730,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
32731,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
32732,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
32733,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
32734,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
32735,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
32736,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
32737,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
32738,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
32739,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
32740,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
32741,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
32742,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
32743,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
32744,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0
32745,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
32746,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0
32747,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
32748,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
32749,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0
32750,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
32751,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
32752,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
32753,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0

In [23]:
model = RandomForestRegressor(100, oob_score=True, n_jobs=-1, random_state=42)
model.fit(X, y)
print "C-stat: ", roc_auc_score(y, model.oob_prediction_)

C-stat:  0.624497833609

In [24]:
from sklearn.metrics import confusion_matrix

In [42]:
model.oob_prediction_

array([[ 0.        ,  1.        ,  0.        , ...,  0.05714286,
         0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.02631579, ...,  0.05263158,
         0.        ,  0.        ],
       [ 0.02777778,  0.08333333,  0.05555556, ...,  0.08333333,
         0.5       ,  0.        ],
       ...,
       [ 0.        ,  0.04255319,  0.34042553, ...,  0.        ,
         0.19148936,  0.        ],
       [ 0.07142857,  0.        ,  0.07142857, ...,  0.38095238,
         0.02380952,  0.        ],
       [ 0.        ,  0.        ,  0.27272727, ...,  0.27272727,
         0.06060606,  0.03030303]])

In [43]:
y_hat = model.oob_prediction_
y_hat

array([[ 0.        ,  1.        ,  0.        , ...,  0.05714286,
         0.        ,  0.        ],
       [ 0.        ,  1.        ,  0.02631579, ...,  0.05263158,
         0.        ,  0.        ],
       [ 0.02777778,  0.08333333,  0.05555556, ...,  0.08333333,
         0.5       ,  0.        ],
       ...,
       [ 0.        ,  0.04255319,  0.34042553, ...,  0.        ,
         0.19148936,  0.        ],
       [ 0.07142857,  0.        ,  0.07142857, ...,  0.38095238,
         0.02380952,  0.        ],
       [ 0.        ,  0.        ,  0.27272727, ...,  0.27272727,
         0.06060606,  0.03030303]])

I wasnt able to figue out where in your code the rounding took place mostly because I'm learning Python on the fly.  I found this nice little code for numpy arrays though, and adjusted it to fit what I was doing.

In [47]:
numpy.around(y_hat, decimals= 0)

array([[ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

Turns out that wasn't the issue though.  :(

In [49]:
confusion_matrix(y, y_hat)

ValueError: Can't handle mix of multilabel-indicator and continuous-multioutput